language: node_js
node_js:
  - "node"

install:
  - npm install google-closure-compiler eslint jsdoc
  - export PATH=$PATH:$(pwd)/node_modules/.bin

script:
  - make lint
  - make doc

deploy:
  provider: pages
  local-dir: doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: ci
